# Generated by Django 4.2.6 on 2023-12-07 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_quantity_cart_nquantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
