# Generated by Django 4.2.6 on 2023-12-07 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_delete_account_delete_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='nquantity',
            new_name='quantity',
        ),
    ]
