# Generated by Django 4.2.5 on 2023-10-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_account_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acctnumber',
            field=models.IntegerField(),
        ),
    ]
