# Generated by Django 4.2.6 on 2023-11-29 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0002_home_rename_description_magazine_mag_descrp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
        migrations.RenameField(
            model_name='magazine',
            old_name='mag_descrp',
            new_name='mag_desc',
        ),
    ]
