# Generated by Django 4.1 on 2024-10-04 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('Employee_name', models.CharField(max_length=100, verbose_name='Employee_name')),
                ('Designation', models.CharField(max_length=100, verbose_name='Designation')),
                ('Gender', models.CharField(max_length=100, verbose_name='Gender')),
                ('Address', models.CharField(max_length=100, verbose_name='Company_Name')),
                ('Phone', models.CharField(max_length=100, verbose_name='Phone')),
                ('Place', models.CharField(max_length=100, verbose_name='Place')),
                ('Email', models.CharField(max_length=100, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, verbose_name='username')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('role', models.CharField(max_length=100, verbose_name='role')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_id', models.AutoField(primary_key=True, serialize=False)),
                ('Product_Name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('Image', models.FileField(upload_to='images/', verbose_name='Image')),
                ('Description', models.CharField(max_length=500, verbose_name='Description')),
                ('Specification', models.CharField(max_length=100, verbose_name='Specification')),
                ('Quantity', models.IntegerField(verbose_name='Quantity')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last_name')),
                ('gender', models.CharField(max_length=100, verbose_name='gender')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='phone_number')),
                ('pincode', models.CharField(max_length=100, verbose_name='pincode')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('state', models.CharField(max_length=100, verbose_name='state')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date_of_birth')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('log_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='managment.login')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('Request_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_date', models.DateField(null=True, verbose_name='from_date')),
                ('Return_Date', models.DateField(null=True, verbose_name='Return_Date')),
                ('Status', models.CharField(max_length=100, verbose_name='Status')),
                ('Penalty', models.CharField(max_length=100, verbose_name='Penalty')),
                ('Defect', models.CharField(max_length=100, verbose_name='Defect')),
                ('Purpose', models.CharField(max_length=100, verbose_name='Purpose')),
                ('Employee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='managment.employee')),
                ('Product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='managment.product')),
            ],
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('penalty_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remark', models.CharField(max_length=255)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penalty_giver', to='managment.employee')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='managment.request')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('ordered', models.BooleanField(default=False)),
                ('noofitems', models.IntegerField()),
                ('address', models.TextField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('order_status', models.CharField(default='pending', max_length=20)),
                ('delivery_status', models.CharField(default='pending', max_length=30)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(to='managment.cartitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managment.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managment.user')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='logid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='managment.login'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managment.product'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managment.user'),
        ),
    ]
