# Generated by Django 4.1 on 2024-10-04 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0002_remove_order_items_remove_order_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managment.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managment.user')),
            ],
        ),
    ]
