# Generated by Django 4.1 on 2024-10-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0004_cart_delete_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='addcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
