# Generated by Django 4.2.6 on 2023-11-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='First',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_title', models.CharField(max_length=200)),
                ('first_desc', models.TextField()),
                ('first_image', models.ImageField(blank=True, null=True, upload_to='news/cover')),
            ],
        ),
    ]
