# Generated by Django 4.2.6 on 2023-12-01 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=100)),
                ('dlocation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_first_name', models.CharField(max_length=100)),
                ('emp_last_name', models.CharField(max_length=100)),
                ('emp_salary', models.IntegerField(default=0)),
                ('emp_bonus', models.IntegerField(default=0)),
                ('emp_phone', models.IntegerField(default=0)),
                ('emp_hire_date', models.DateField()),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.department')),
                ('emp_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.role')),
            ],
        ),
    ]
