# Generated by Django 4.2.6 on 2023-12-01 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_department_role_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emp_role',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
