# Generated by Django 4.2.6 on 2023-10-31 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
