# Generated by Django 4.2.6 on 2023-12-03 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0006_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='news_Type',
        ),
    ]
