# Generated by Django 4.2.6 on 2023-12-03 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0007_rename_type_news_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news_type',
            old_name='available',
            new_name='navailable',
        ),
        migrations.RenameField(
            model_name='news_type',
            old_name='created',
            new_name='ncreated',
        ),
        migrations.RenameField(
            model_name='news_type',
            old_name='description',
            new_name='ndesc',
        ),
        migrations.RenameField(
            model_name='news_type',
            old_name='news',
            new_name='newspaper',
        ),
        migrations.RenameField(
            model_name='news_type',
            old_name='image',
            new_name='nimage',
        ),
        migrations.RenameField(
            model_name='news_type',
            old_name='price',
            new_name='nprice',
        ),
        migrations.RenameField(
            model_name='news_type',
            old_name='stock',
            new_name='nstock',
        ),
        migrations.RenameField(
            model_name='news_type',
            old_name='typname',
            new_name='ntypname',
        ),
        migrations.RenameField(
            model_name='news_type',
            old_name='updated',
            new_name='nupdated',
        ),
    ]
