# Generated by Django 4.2.6 on 2023-12-07 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0010_rename_nstock_news_type_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news_type',
            old_name='nprice',
            new_name='price',
        ),
    ]
