# Generated by Django 4.2.6 on 2023-12-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0011_rename_nprice_news_type_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='videos/')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
